name: Documentation
title: "[<Agent component: framework|tool|llm|etc...>] "
description: Report an issue with the Modelscope-agent documentation
labels: [docs, triage]
body:
  - type: markdown
    attributes:
      value: Thank you for helping us improve the Modelscope-agent documentation and demo!

  - type: textarea
    attributes:
      label: Description
      description: |
        Tell us about the change you'd like to see. For example, "I'd like to
        see more examples of how to create a new tool."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Link
      description: |
        If the problem is related to an existing section, please add a link to
        the section. For example, https://github.com/modelscope/modelscope-agent/blob/master/demo/demo_alpha_umi.ipynb.
    validations:
      required: false
