name: Modelscope-Agent feature request
description: Suggest an idea for Modelscope-Agent project
title: "[<Agent component: framework|tool|llm|etc...>] "
labels: [enhancement]
assignees:
  - zzhangpurdue
  - suluyana

body:
  - type: markdown
    attributes:
      value: |
        Thank you for finding the time to propose a new feature!
        We really appreciate the community efforts to improve Modelscope-Agent.

  - type: checkboxes
    id: searched
    attributes:
      label: Initial Checks
      description: |
        Just a few checks to make sure you need to create a feature request.

        _Sorry to sound so draconian 👿; but every second spent replying to issues is time not spent improving Modelscope-Agent 🙇._
      options:
        - label: I have searched Google & GitHub for similar requests and couldn't find anything
          required: true
        - label: I have read and followed [the docs & demos](https://github.com/modelscope/modelscope-agent/tree/master/demo) and still think this feature is missing
          required: true

  - type: textarea
    attributes:
      label: Description
      description: A short description of your feature

  - type: textarea
    attributes:
      label: Use case
      description: >
        Describe the use case of your feature request. It will help us understand and
        prioritize the feature request.
      placeholder: >
        Rather than telling us how you might implement this feature, try to take a
        step back and describe what you are trying to achieve.
