version: '3'

services:
  tool_manager_service:
    build:
      context: ../
      dockerfile: docker/tool_manager.dockerfile
    ports:
      - "31511:31511"
    entrypoint: uvicorn tool_service.tool_manager.api:app --host 0.0.0.0 --port 31511
