FROM registry.cn-beijing.aliyuncs.com/modelscope-repo/modelscope:ubuntu20.04-py38-torch2.0.1-tf2.13.0-1.9.5

RUN apt update && apt-get install -y curl wget inetutils-ping vim less
RUN pip install gunicorn gradio dashscope "datasets>=2.8.0" ipython "langchain<=0.0.292" "modelscope>=1.7.0" moviepy ms-swift openai opencv-python openpyxl Pillow "pydantic>=2.0.0" pypdf pytest python-dotenv soundfile "transformers>=4.29.0" transformers_stream_generator docx2txt python-pptx

COPY requirements.txt /home/workspace/requirements.txt
RUN pip install -r /home/workspace/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

COPY . /home/workspace

WORKDIR /home/workspace/apps/agentfabric
